/*
 * HEAT_COOL_RELAY.c
 *
 * Created: 12-Dec-21 9:48:05 PM
 *  Author: ADMIN
 */ 
#include "HEAT_COOL_RELAY_CFG.h"
#include "DIO.h"

void HEATING_RELAY_INIT (void)
{
	PIN_MODE(HEATING_RELAY_PIN,OUTPUT);
}
void HEATING_RELAY_ON   (void)
{
	PIN_WRITE(HEATING_RELAY_PIN,HIGH);
}
void HEATING_RELAY_OFF  (void)
{
	PIN_WRITE(HEATING_RELAY_PIN,LOW);
}
void COOLING_RELAY_INIT (void)
{
	PIN_MODE(COOLING_RELAY_PIN,OUTPUT);
}
void COOLING_RELAY_ON   (void)
{
	PIN_WRITE(COOLING_RELAY_PIN,HIGH);
}
void COOLING_RELAY_OFF  (void)
{
	PIN_WRITE(COOLING_RELAY_PIN,LOW);
}